version: "3.8"

services:
  mysqldb: 
    container_name: mysqldb
    image: mysql:latest
    ports: 
     - 3306:3306   
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
    - 6379:6379 
  
  demo_nave:
    container_name: demo_nave
    build: ./demo
    ports:
      - 8080:8080
    environment:
       MYSQL_HOST: mysqldb
       MYSQL_PORT: 3306
       REDIS_HOST: redis
       REDIS_PORT: 6379
    depends_on:
      - mysqldb
      - redis

volumes:
  db:
